#!/bin/sh
# Debian-specific setup-plt.  It is based on the original setup-plt,
# but it installs in local directories.  The regular setup-plt is also
# installed, and it places things in /usr/lib/plt
if [ "$PLTCOLLECTS" = '' ] ; then
  PLTCOLLECTS=/usr/local/lib/plt/collects:/usr/lib/plt/collects
  export PLTCOLLECTS
fi

# Debian installation
if [ "$PLTHOME" = '' ] ; then
  PLTHOME=/usr/local/lib/plt
  export PLTHOME
fi

exec /usr/bin/mzscheme '-mqvL' 'setup.ss' 'setup' '--'   ${1+"$@"}
