.\" dummy line
.TH HELP-DESK 1 "1 October 2000"
.UC 4
.SH NAME
help-desk \- PLT Help Browser
.SH SYNOPSIS
.B help-desk
[
.I Xflag ...
]
.SH DESCRIPTION
.I help-desk
is a launcher for the PLT DrScheme runtime environment that starts
up the help browsing facility for the various PLT documentation
installed on the system.
.PP
For further information on
.I MzScheme,
.I DrScheme,
or any of its components (such as setup-plt) please 
consult the on-line documentation and other information 
available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/drscheme/
.SH FILES
.I DrScheme
looks for its libraries using the environment variables
PLTHOME and PLTCOLLECTS.  If this variable is not defined,
the installation directory is assumed ("/usr/lib/plt/" on
Debian systems). See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
Help Desk (encouraged),
or via the web
.ce 1
http://www.cs.rice.edu/CS/PLT/Bugs/ (discouraged)
or by e-mail to
.ce 1
plt-bugs@cs.rice.edu (discouraged)
.SH AUTHOR
.I DrScheme
was implemented by Robby Findler (robby@cs.rice.edu),
Shriram Krishnamurthi (shriram@cs.rice.edu), Cormac Flanagan 
(cormac@cs.rice.edu), Matthew Flatt (mflatt@cs.rice.edu),
and Paul Steckler (steck@cs.rice.edu).
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1)
