.\" dummy line
.TH DRSCHEME 1 "28 October 1999"
.UC 4
.SH NAME
setup-plt \- The Rice PLT Scheme Setup Utility
.SH SYNOPSIS
.B setup-plt
[
.I Xflag ...
]
[
.I file ...
]
.SH DESCRIPTION
.I setup-plt
is the Rice University PLT Scheme
Setup Utility.
.PP
.I setup-plt
installs the .plt files given as command-line arguments.
It installs the files into the root PLT directory
(/usr/lib/plt on Debian systems) and compiles the source
into *.zo files.
.pp
This command should generally be used by Debian setup scripts
(and the automated tools associated with MzScheme/DrScheme).
Local administrators should maintain their local PLT files
via the debian-plt script, which places things in the
/usr/local/lib/plt directory.
.pp
For further information on
.I MzScheme,
.I DrScheme,
or any of its components (such as setup-plt) please 
consult the on-line documentation and other information 
available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/drscheme/
.SH FILES
.I DrScheme
looks for its libraries using the environment variables
PLTHOME and PLTCOLLECTS.  If this variable is not defined,
the installation directory is assumed ("/usr/local/lib/plt/" on
Debian systems). See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
Help Desk (encouraged),
or via the web
.ce 1
http://www.cs.rice.edu/CS/PLT/Bugs/ (discouraged)
or by e-mail to
.ce 1
plt-bugs@cs.rice.edu (discouraged)
.SH AUTHOR
.I DrScheme
was implemented by Robby Findler (robby@cs.rice.edu),
Shriram Krishnamurthi (shriram@cs.rice.edu), Cormac Flanagan 
(cormac@cs.rice.edu), Matthew Flatt (mflatt@cs.rice.edu),
and Paul Steckler (steck@cs.rice.edu).
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1)
