.\" dummy line
.TH SLIDESHOW 1 "1 October 2000"
.UC 4
.SH NAME
slidehow \- The PLT Scheme Web Server
.SH SYNOPSIS
.B slidehow
[
.I Xflag ...
]
.SH DESCRIPTION
.I slidehow
is a launcher for the PLT DrScheme runtime environment operating
as a presentation manager.  It allows dynamic content using
a form of Scheme markup.
.PP
For further information on
.I MzScheme,
.I DrScheme,
or any of its components (such as setup-plt) please 
consult the on-line documentation and other information 
available at
.PP
.ce 1
http://www.cs.rice.edu/CS/PLT/packages/drscheme/
.SH FILES
.I DrScheme
looks for its libraries using the environment variables
PLTHOME and PLTCOLLECTS.  If this variable is not defined,
the installation directory is assumed ("/usr/lib/plt/" on
Debian systems). See the documentation for details.
.PP
Please consult your local administrator to determine whether
the on-line documentation has been installed locally.
.SH BUGS
Submit bug reports via
.ce 1
Help Desk (encouraged),
or via the web
.ce 1
http://www.cs.rice.edu/CS/PLT/Bugs/ (discouraged)
or by e-mail to
.ce 1
plt-bugs@cs.rice.edu (discouraged)
.SH AUTHOR
.I DrScheme
was implemented by Robby Findler (robby@cs.rice.edu),
Shriram Krishnamurthi (shriram@cs.rice.edu), Cormac Flanagan 
(cormac@cs.rice.edu), Matthew Flatt (mflatt@cs.rice.edu),
and Paul Steckler (steck@cs.rice.edu).
.SH SEE ALSO
.BR mred(1),
.BR mzscheme(1)
