name: CI Win

on: [push, pull_request]

jobs:
  
# Build jobs
# These jobs build each Racket component separately and tests on the component start as soon as each
# component finishes building.
  buildtest-win:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        mode: ['3m', 'CS']
    
    # According to
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019
    # VS2019 is what is installed in the hosted runners:
    #   Version: VisualStudio/16.3.6+29418.71
    #   Location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    steps:
    - uses: actions/checkout@v2
    - name: Build 3m
      working-directory: .\racket\src\worksp
      if: matrix.mode == '3m'
      shell: cmd
      run: |
        call msvcprep.bat x86_amd64
        call build.bat
    - name: Build CS
      working-directory: .\racket\src\worksp
      if: matrix.mode == 'CS'
      shell: cmd
      run: |
        call msvcprep.bat x86_amd64
        call build-cs.bat
    - name: Check reported racket version
      shell: cmd
      run: |
        call racket\racket.exe --version
    - name: Install Testing Deps
      shell: cmd
      run: |
        call racket\raco.exe pkg install --auto --no-docs racket-test unstable-flonum-lib net-test
    - name: Test
      shell: cmd
      run: |
        call racket\raco.exe test -l tests/racket/test
        call racket\racket.exe -l tests/racket/contract/all
        call racket\raco.exe test -l tests/json/json
        call racket\raco.exe test -l tests/file/main
        call racket\raco.exe test -l tests/net/head
        call racket\raco.exe test -l tests/net/uri-codec
        call racket\raco.exe test -l tests/net/url
        call racket\raco.exe test -l tests/net/url-port
        call racket\raco.exe test -l tests/net/encoders
        call racket\raco.exe test -l tests/openssl/basic
        call racket\raco.exe test -l tests/openssl/https
        call racket\raco.exe test -l tests/match/main
        call racket\raco.exe test -l tests/zo-path
        call racket\raco.exe test -c tests/xml
        call racket\raco.exe test -c tests/future
        call racket\raco.exe test -l tests/db/all-tests
        racket\raco.exe test -c tests/stxparse
