name: ARM64 Linux Fast Build

on: [pull_request]

jobs:
  build-racket3m:
    if: github.repository == 'racket/racket'
    container:
      image: racket/racket-ci:latest
                
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Build Racket 3m
      run: make CPUS=$(nproc) PKGS="" bc-in-place

  build-racketcs:
    if: github.repository == 'racket/racket'
    container:
      image: racket/racket-ci:latest

    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Build Racket CS
      run: make CPUS=$(nproc) PKGS="" cs-in-place
